# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 452)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.coeffsLabel = QtWidgets.QLabel(Form)
        self.coeffsLabel.setObjectName("coeffsLabel")
        self.verticalLayout.addWidget(self.coeffsLabel)
        self.coeffsLineEdit = QtWidgets.QLineEdit(Form)
        self.coeffsLineEdit.setObjectName("coeffsLineEdit")
        self.verticalLayout.addWidget(self.coeffsLineEdit)
        self.textHorizontalLayout = QtWidgets.QHBoxLayout()
        self.textHorizontalLayout.setObjectName("textHorizontalLayout")
        self.leftTextVerticalLayout = QtWidgets.QVBoxLayout()
        self.leftTextVerticalLayout.setObjectName("leftTextVerticalLayout")
        self.leftTextLabel = QtWidgets.QLabel(Form)
        self.leftTextLabel.setObjectName("leftTextLabel")
        self.leftTextVerticalLayout.addWidget(self.leftTextLabel)
        self.leftTextBrowser = QtWidgets.QTextBrowser(Form)
        self.leftTextBrowser.setReadOnly(False)
        self.leftTextBrowser.setObjectName("leftTextBrowser")
        self.leftTextVerticalLayout.addWidget(self.leftTextBrowser)
        self.textHorizontalLayout.addLayout(self.leftTextVerticalLayout)
        self.rightVerticalLayout = QtWidgets.QVBoxLayout()
        self.rightVerticalLayout.setObjectName("rightVerticalLayout")
        self.rightTextLabel = QtWidgets.QLabel(Form)
        self.rightTextLabel.setObjectName("rightTextLabel")
        self.rightVerticalLayout.addWidget(self.rightTextLabel)
        self.rightTextBrowser = QtWidgets.QTextBrowser(Form)
        self.rightTextBrowser.setObjectName("rightTextBrowser")
        self.rightVerticalLayout.addWidget(self.rightTextBrowser)
        self.textHorizontalLayout.addLayout(self.rightVerticalLayout)
        self.verticalLayout.addLayout(self.textHorizontalLayout)
        self.changeModePushButton = QtWidgets.QPushButton(Form)
        self.changeModePushButton.setObjectName("changeModePushButton")
        self.verticalLayout.addWidget(self.changeModePushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Trithemius cipher"))
        self.coeffsLabel.setText(_translate("Form", "Введите коэффициенты уравнения смещения через пробел:"))
        self.coeffsLineEdit.setText(_translate("Form", "0"))
        self.leftTextLabel.setText(_translate("Form", "Открытый текст"))
        self.rightTextLabel.setText(_translate("Form", "Закрытый текст"))
        self.changeModePushButton.setText(_translate("Form", "Режим шифрования"))
